### ISSUE TITLE
Crash on Auto-Identify

### ISSUE THREAD

**Issue by DieselTech** [comictagger/gcd_talker#1]
Looks like it encounters an error displaying the data in rows when showing the selection screen:

![image](https://github.com/mizaki/comictagger-gcd-talker/assets/30128380/a116905d-5432-4bab-9cf4-cb929c4e6052)

**Comment by mizaki** [comment]
That's a CT crash, I've already put a in https://github.com/comictagger/comictagger/pull/521 You should see the same with any talker.
