### ISSUE TITLE
web link don´t working with comictagger´s multiple web links

### ISSUE THREAD

**Issue by Vertigooo2** [comictagger/gcd_talker#12]
After the change in comictagger for multiple links ([Support multiple web_links)](https://github.com/comictagger/comictagger/pull/601), it is necessary to adapt gcd_talker. I have tested that it works again by making the following changes:

- add:

`from urllib3.util import parse_url`

- replace:

`md.web_link = urljoin(self.website, f"issue/{issue['id']}")`

with:

`md.web_links = [parse_url(urljoin(self.website, f"issue/{issue['id']}"))]`

**Comment by mizaki** [comment]
#10 has the change with an expected new alpha but it might not appear so I'll remove that and push it through because the master "aims" to be up-to-date with CT develop.

**Comment by mizaki** [comment]
I lied about taking the min version, it should work with master as long as your `ctversion.py` has been created recently.

**Comment by mizaki** [comment]
Fixed in #10
