### ISSUE TITLE
Attempt to download covers for the GUI only works for series not issues

### ISSUE THREAD

**Issue by lordwelch** [comictagger/gcd_talker#5]
When the "Attempt to download covers for the GUI" option is enabled the Series Selection Window shows the image for the first issue but the Issue Selection Window does not show any images
<img width="1062" alt="Screenshot 2023-12-17 at 7 00 02 PM" src="https://github.com/mizaki/gcd_talker/assets/7547075/722efe4e-5c7f-4915-a8e4-d83a64d48537">
<img width="984" alt="Screenshot 2023-12-17 at 7 00 08 PM" src="https://github.com/mizaki/gcd_talker/assets/7547075/73553154-9137-4898-bfe3-95bf94ca4337">

**Comment by mizaki** [comment]
Works fine for me. There is no limiter on the downloads right now so it's possible you activated CloudFlare. Is there anything in the log? I don't expect `requests.exceptions.RequestException` will activate. Adding a check for a CF reply is needed.

If that is it, going to the website page for the series/issue should get you a captcha.

**Comment by lordwelch** [comment]
I don't see anything useful in the log. And it consistently works for the series just not for the issue. I also tested by searching naruto and a handful of the series will populate an image but none of the issues will populate.
[ComicTagger.log](https://github.com/mizaki/gcd_talker/files/13723209/ComicTagger.log)

**Comment by mizaki** [comment]
Still need to add the CloudFlare check.
