### ISSUE TITLE
Auto-identify fails if the year is set

### ISSUE THREAD

**Issue by lordwelch** [comictagger/gcd_talker#7]
Attempting to auto-identify this archive fails https://github.com/comictagger/comictagger/blob/develop/testing/data/Cory%20Doctorow's%20Futuristic%20Tales%20of%20the%20Here%20and%20Now%20%23001%20-%20Anda's%20Game%20(2007).cbz when the year is set even though the year is correct and listed in the database.
Here is a log showing that two attempts to auto-identify fail and once the year is removed the auto-identify succeeds.
[ComicTagger.log](https://github.com/mizaki/gcd_talker/files/14003086/ComicTagger.log)

**Comment by mizaki** [comment]
The issue is the issues have no `key_date` on them.
