### ISSUE TITLE
Story titles not in order

### ISSUE THREAD

**Issue by mizaki** [comictagger/gcd_talker#8]
When the story titles are concatenated together they are not ordered by `sequence_number`. (`GROUP_CONCAT` does not support `ORDER BY` in SQLite)

**Comment by Vertigooo2** [comment]
Hi!

After trying several methods, the one that worked for me was [this](https://stackoverflow.com/a/23783461).

I have created a function to sort the titles according to sequence number: `split_issue_titles`

I have attached modified gcd.py. I have tested it and it works correctly.

[gcd.zip](https://github.com/user-attachments/files/16106568/gcd.zip)

**Comment by mizaki** [comment]
I've finally gotten around to looking at this and it appears as if the story order is simply reversed. Going by the docs the order is not guaranteed but it's taken to mean that it "could" change but the order is still the same each time and not random. If this is the case then a simple `reverse` would do the trick.

@Vertigooo2 I wondered in your testing if you noticed any issues where the story order from the query was not in reverse order?

**Comment by mizaki** [comment]
I've done the reverse for now but have #28 ready to go if needed. Let me know any problem comics if you find any.

**Comment by mizaki** [comment]
It appears that <10 story titles are reversed but >9 are not.

lordwelch solution:
```SQL
SELECT 
  gcd_issue.id AS 'id', 
  gcd_issue.number AS 'number', 
  gcd_issue.key_date AS 'key_date', 
  gcd_issue.title AS 'issue_title', 
  gcd_issue.series_id AS 'series_id', 
  (
    select 
      json_group_array(json_array(gcd_story.sequence_number,gcd_story.title)) 
    from 
      gcd_story 
    where 
      (
        gcd_story.issue_id = gcd_issue.id 
        and gcd_story.type_id = 19 
        AND gcd_issue.variant_of_id IS NULL 
        AND gcd_story.title IS NOT NULL 
        AND gcd_story.title != ''
      ) 
    ORDER BY 
      gcd_story.sequence_number DESC
  ) AS 'story_titles' 
FROM 
  gcd_issue 
where 
  gcd_issue.series_id = 1235 
GROUP BY 
  gcd_issue.id;
```

```python
[x[1] for x in sorted(row['story_titles')]
```
